name: Build APK

env:
  APKTOOL_VER: 2.9.0

on:
  push:
    branches: 
      - 14

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - uses: robinraju/release-downloader@v1.5
      with:
        repository: 'iBotPeaches/Apktool'
        tag: 'v${{ env.APKTOOL_VER }}'
        fileName: 'apktool_${{ env.APKTOOL_VER }}.jar'

    - run: java -jar apktool_${{ env.APKTOOL_VER }}.jar b .

    - uses: actions/upload-artifact@v3
      with:
        name: APK
        path: dist/ImsService.apk
